enforce uniqueness of schema `id` fields
hrxp/api pull request #11
Opened 2019-07-30 22:11 UTC by shockey

This should keep us from making a mess of our collections, since we're planning to keep track of what we do and don't already have in the DB based on Slack's IDs.

2019-07-30 23:11 UTC, spraguejdev requested changes
Mongo creates it's own unique id field. My questions is, are we going to be creating the scheima id field ourselves?

2019-07-30 23:29 UTC, miken619 commented
> Mongo creates it's own unique id field. My questions is, are we going to be creating the scheima id field ourselves?

I'm guessing it so we can grab data using the id we defined?

2019-07-30 23:30 UTC, miken619 approved these changes

2019-07-31 21:46 UTC, spraguejdev approved these changes

2019-07-31 21:47 UTC, merged